# configs/tv.yaml

category: tv

api_token_primary:  "AIzaSyCF8qX-WgtjiNcs5qjRkF77e35_eIfPKCo"
api_token_secondary: "AIzaSyA0cym0jtA3LUQfuhvlP2OAf6Dexg_UO0Q"

urls:
  - source: amazon
    url: "https://www.amazon.in/Samsung-inches-Frame-Smart-QA55LS03BAKLXL/dp/B09Y658WHN"

  - source: flipkart
    url: "https://www.flipkart.com/samsung-frame-138-cm-55-inch-qled-ultra-hd-4k-smart-tizen-tv-matte-display/p/itm7a92ace0cdc14"
